MVCGarage/Models/ParkingSpot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCGarage.Models
{
    public class ParkingSpot
    {
        [Key]
        [Display(Name = "ID")]
        public int ID { get; set; }

        [Display(Name = "Identifiant")]
        public string Label { get; set; }

        [Display(Name = "Fee")]
        public double? Fee { get; set; }

        public double GetFee()
        {
            if (Fee == null)
                return 0;
            else
                return (double)(Fee);
        }

        public string DisplayFee()
        {
            return string.Format("{0:C}/min.", GetFee());
        }

        public string DisplayMonthlyFee()
        {
            return string.Format("{0:C}/month", MonthlyFee());
        }

        [Display(Name = "Monthly fee")]
        public double MonthlyFee()
        {
            return Math.Round(70 * 30 * 24 * 60 * GetFee() / 100, 2, MidpointRounding.AwayFromZero);
        }

        // Navigation property - Allows the 1..1 relation to the "VehicleType" table
        [ForeignKey("VehicleType")]
        [Display(Name="Vehicle Type")]
        public int VehicleTypeID { get; set; }

        [Display(Name = "Vehicle Type")]
        public virtual VehicleType VehicleType { get; set; }
        // --- //

        // Navigation property - Allows the 1..* relation to the "CheckIn" table
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        // --- //
    }
}

MVCGarage/ViewModels/ParkingSpots/CreateParkingSpotsVM.cs
using MVCGarage.Models;
using System.Collections.Generic;

namespace MVCGarage.ViewModels.ParkingSpots
{
    public class CreateParkingSpotsVM
    {
        public ParkingSpot ParkingSpot { get; set; }
        public IEnumerable<DefaultFee> DefaultFees { get; set; }
        public string ErrorMessage { get; set; }
    }
}

MVCGarage/ViewModels/ParkingSpots/EditParkingSpotVM.cs
using MVCGarage.Models;

namespace MVCGarage.ViewModels.ParkingSpots
{
    public class EditParkingSpotVM
    {
        public ParkingSpot ParkingSpot { get; set; }
        public Vehicle ParkedVehicle { get; set; }
    }
}

MVCGarage/ViewModels/ParkingSpots/SelectAParkingSpotVM.cs
using MVCGarage.Models;
using System.Collections.Generic;

namespace MVCGarage.ViewModels.ParkingSpots
{
    public class SelectAParkingSpotVM
    {
        public int VehicleID { get; set; }
        public Vehicle SelectedVehicle { get; set; }

        public IEnumerable<ParkingSpot> ParkingSpots { get; set; }
        public int ParkingSpotID { get; set; }
        public bool CheckIn { get; set; }

        public string ErrorMessage { get; set; }
    }
}

MVCGarage/Controllers/CheckInsController.cs
using MVCGarage.Models;
using MVCGarage.Repositories;
using MVCGarage.ViewModels.CheckIns;
using MVCGarage.ViewModels.ParkingSpots;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVCGarage.Controllers
{
    public class CheckInsController : Controller
    {
        private CheckInsRepository db = new CheckInsRepository();

        private IEnumerable<CheckIn> Sort(IEnumerable<CheckIn> list, string sortOrder)
        {
            ViewBag.CheckInIDSortParam = string.IsNullOrEmpty(sortOrder) ? "id_desc" : "id_asc";

            ViewBag.ParkingSpotLabelSortParam = sortOrder == "label_asc" ? "label_desc" : "label_asc";

            ViewBag.VehicleRegNumberSortParam = sortOrder == "regnum_asc" ? "regnum_desc" : "regnum_asc";
            ViewBag.VehicleOwnerSortParam = sortOrder == "owner_asc" ? "owner_desc" : "owner_asc";

            ViewBag.CheckInTimeSortParam = sortOrder == "checkintime_asc" ? "checkintime_desc" : "checkintime_asc";
            ViewBag.CheckOutTimeSortParam = sortOrder == "checkouttime_asc" ? "checkouttime_desc" : "checkouttime_asc";
            ViewBag.TotalAmountSortParam = sortOrder == "totalamount_asc" ? "totalamount_desc" : "totalamount_asc";
            ViewBag.StatusSortParam = sortOrder == "status_asc" ? "status_desc" : "status_asc";

            switch (sortOrder)
            {
                case "id_asc":
                    list = list.OrderBy(ch => ch.ID);
                    break;
                case "label_asc":
                    list = list.OrderBy(ch => ch.ParkingSpot.Label);
                    break;
                case "label_desc":
                    list = list.OrderByDescending(ch => ch.ParkingSpot.Label);
                    break;
                case "regnum_asc":
                    list = list.OrderBy(ch => ch.Vehicle.RegistrationPlate);
                    break;
                case "regnum_desc":
                    list = list.OrderByDescending(ch => ch.Vehicle.RegistrationPlate);
                    break;
                case "owner_asc":
                    list = list.OrderBy(ch => ch.Vehicle.Owner);
                    break;
                case "owner_desc":
                    list = list.OrderByDescending(ch => ch.Vehicle.Owner);
                    break;
                case "checkintime_asc":
                    list = list.OrderBy(ch => ch.CheckInTime);
                    break;
                case "checkintime_desc":
                    list = list.OrderByDescending(ch => ch.CheckInTime);
                    break;
                case "checkouttime_asc":
                    list = list.OrderBy(ch => ch.CheckOutTime);
                    break;
                case "checkouttime_desc":
                    list = list.OrderByDescending(ch => ch.CheckOutTime);
                    break;
                case "totalamount_asc":
                    list = list.OrderBy(ch => ch.TotalAmount);
                    break;
                case "totalamount_desc":
                    list = list.OrderByDescending(ch => ch.TotalAmount);
                    break;
                case "status_asc":
                    list = list.OrderBy(ch => ch.Status());
                    break;
                case "status_desc":
                    list = list.OrderBy(ch => ch.Status());
                    break;
                default:
                    list = list.OrderByDescending(ch => ch.ID);
                    break;
            }

            return list;
        }

        [HttpGet]
        public ActionResult VehicleHistoric(int? vehicleId, string sortOrder)
        {
            if (vehicleId == null)
                return RedirectToAction("Index", "Garage");

            return View(new VehicleHistoricVM
            {
                Vehicle = new GarageController().Vehicle(vehicleId),
                CheckIns = Sort(db.CheckInsByVehicle((int)vehicleId), sortOrder).ToList()
            });
        }

        [HttpGet]
        public ActionResult ParkingSpotHistoric(int? parkingSpotId, string sortOrder)
        {
            if (parkingSpotId == null)
                return RedirectToAction("Index", "Garage");

            return View(new ParkingSpotHistoricVM
            {
                ParkingSpot = new GarageController().ParkingSpot(parkingSpotId),
                CheckIns = Sort(db.CheckInsByParkingSpot((int)parkingSpotId), sortOrder).ToList()
            });
        }

        [HttpGet]
        public ActionResult VehicleCheckedIn(SelectAParkingSpotVM viewModel)
        {
            // Check that the vehicle isn't already parked/hasn't booked a place
            if (db.CheckInByVehicle(viewModel.VehicleID) != null)
                return RedirectToAction("Index", "Garage");

            Vehicle vehicle = new GarageController().Vehicle(viewModel.VehicleID);

            if (vehicle == null)
                return RedirectToAction("BookAParkingSpot",
                                        "Vehicles",
                                        new
                                        {
                                            checkIn = viewModel.CheckIn,
                                            errorMessage = "You must select a vehicle!"
                                        });

            // Check in the vehicle ID to the parking spot
            ParkingSpot parkingSpot = new GarageController().ParkingSpot(viewModel.ParkingSpotID);

            if (parkingSpot == null)
                return RedirectToAction("CheckInAVehicle", new
                {
                    vehicleId = viewModel.VehicleID,
                    errorMessage = "You must select a parking spot!"
                });

            CheckIn checkIn = db.CheckIn(viewModel.VehicleID, viewModel.ParkingSpotID);
            checkIn.Vehicle = vehicle;
            checkIn.ParkingSpot = parkingSpot;

            // Displays the chosen parking spot
            return View(checkIn);
        }

        [HttpGet]
        public ActionResult VehicleCheckedOut(int? vehicleId)
        {
            if (vehicleId == null)
                return RedirectToAction("Index", "Garage");

            CheckIn checkIn = new CheckInsVehicles().CheckInByVehicle((int)vehicleId);

            if (checkIn == null)
                return RedirectToAction("Index", "Garage");

            // Check out the vehicle ID to the parking spot
            DateTime now = DateTime.Now;
            int nbMinutes = (int)Math.Truncate((now - (DateTime)checkIn.CheckInTime).TotalMinutes) + 1;
            double totalAmount = nbMinutes * checkIn.ParkingSpot.VehicleType.DefaultFee.Fee;

            checkIn = db.CheckOut(checkIn.ID, now, totalAmount);

            // Displays the bill
            return View(new VehicleCheckedOutVM
            {
                CheckIn = checkIn,
                NbMinutes = nbMinutes
            });
        }

        [HttpGet]
        public ActionResult ParkingSpotBooked(SelectAParkingSpotVM viewModel)
        {
            // Check that the vehicle isn't already parked/hasn't booked a place
            if (db.CheckInByVehicle(viewModel.VehicleID) != null)
                return RedirectToAction("Index", "Garage");

            // Check in the vehicle ID to the parking spot
            CheckIn checkIn = db.Book(viewModel.VehicleID, viewModel.ParkingSpotID);
            checkIn.Vehicle = new GarageController().Vehicle(viewModel.VehicleID);
            checkIn.ParkingSpot = new GarageController().ParkingSpot(viewModel.ParkingSpotID);

            // Displays the chosen parking spot
            return View(checkIn);
        }

        [HttpGet]
        public ActionResult ParkingSpotUnbooked(int? vehicleId)
        {
            if (vehicleId == null)
                return RedirectToAction("Index", "Garage");

            CheckIn checkIn = new CheckInsVehicles().CheckInByVehicle((int)vehicleId);

            if (checkIn == null)
                return RedirectToAction("Index", "Garage");

            // Check out the vehicle ID to the parking spot
            DateTime now = DateTime.Now;
            int nbMonths = (int)Math.Truncate((now - (DateTime)checkIn.CheckInTime).TotalDays / 30) + 1;
            double totalAmount = nbMonths * checkIn.ParkingSpot.MonthlyFee();

            checkIn = db.CheckOut(checkIn.ID, now, totalAmount);

            // Displays the bill
            return View(new ParkingSpotUnbookedVM
            {
                CheckIn = checkIn,
                NbMonths = nbMonths
            });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCGarage/Views/ParkingSpots/Create.cshtml
@model MVCGarage.ViewModels.ParkingSpots.CreateParkingSpotsVM

@{
    ViewBag.Title = "Create a new parking spot";
}

<div class="header jumbotron">
    <h1>Create a parking spot</h1>
    <hr />
    <p>This is where you can create a new parking spot</p>
    <p style="color:red">@Model.ErrorMessage</p>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal about-body-text" style="color: white; font-size: 1em;">
        <h2 style="text-align:center;">ParkingSpot</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ParkingSpot.VehicleType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ParkingSpot.VehicleTypeID,
                                      (IEnumerable<SelectListItem>)ViewBag.SelectVehicleTypes,
                                      htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParkingSpot.VehicleTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.ParkingSpot.Label, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParkingSpot.Label,
                new
                {
                    htmlAttributes = new
                    {
                        @class = "form-control",
                        placeholder = "Spot's label",
                        required = "required"
                    }
                })
                @Html.ValidationMessageFor(model => model.ParkingSpot.Label, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.ParkingSpot.VehicleType.DefaultFee.Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ Html.EnableClientValidation(false); }
                @{
                    string toolTip = "Default fee values:";
                    toolTip += string.Format("{0}{1}{0}", Environment.NewLine, new string('-', 19));
                    foreach (MVCGarage.Models.DefaultFee defaultFee in Model.DefaultFees)
                    {
                        string text = string.Format("{0}: {1:N2}/min.",
                                                    defaultFee.VehicleType.Type,
                                                    defaultFee.Fee);

                        toolTip += string.Format("{0}{1}",
                                                 text,
                                                 string.Format("{0}{1}{0}",
                                                               Environment.NewLine,
                                                               new string('-', text.Length)));
                    }
                }
                @Html.EditorFor(model => model.ParkingSpot.VehicleType.DefaultFee.Fee,
                                new
                                {
                                    htmlAttributes = new
                                    {
                                        @class = "form-control",
                                        placeholder = "Hover for info about default values",
                                        @title = toolTip
                                    }
                                })
                @{ Html.EnableClientValidation(true); }
                @Html.ValidationMessageFor(model => model.ParkingSpot.VehicleType.DefaultFee.Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCGarage/Views/ParkingSpots/Delete.cshtml
@model MVCGarage.Models.ParkingSpot

@{
    ViewBag.Title = "Delete a Parking Spot";
}

<div class="header jumbotron">
    <h1>Delete a parking spot</h1>
    <hr />
    <p>This is where you can go to delete a parking spot</p>
</div>


<h1 style="color: white; text-align: center;">Are you sure you want to delete this parking spot?</h1>
<div class="about-body-text" style="color: white;">
    <h5 style="text-align: center;">ParkingSpot</h5>
    <hr />
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Label)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VehicleType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fee)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Label)
                </td>
                <td>
                    @Html.DisplayFor(model => model.VehicleType.Type)
                </td>
                <td>
                    @Model.DisplayFee()
                </td>
            </tr>
        </table>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="text-align: center; display: block; margin-bottom: 3em;">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCGarage/Views/ParkingSpots/Details.cshtml
@model MVCGarage.ViewModels.Shared.DetailsParkingSpotVM

@{
    ViewBag.Title = "Parking spot details";
}

<div class="header jumbotron">
    <h2>Details</h2>
    <hr />
    <p>View the details of the parking spot</p>
</div>

<div class="jumbotron" style="color: white; font-size: 1.35em;">
    <h2>ParkingSpot</h2>
    <hr />

    @{
        bool available = false;
        bool parked = false;

        if (Model.CheckIn == null)
        {
            available = true;
        }
        else
        {
            parked = !Model.CheckIn.Booked;
        }
    }

    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayName("Availibility")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ParkingSpot.Label)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ParkingSpot.VehicleType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ParkingSpot.Fee)
                </th>
            </tr>
            <tr>
                <td>
                    @{
                        if (available)
                        {
                            @Html.DisplayName("Available")
                        }
                        else if (parked)
                        {
                            @Html.DisplayName(string.Format("Taken by {0} ({1})",
                                                            Model.CheckIn.Vehicle.RegistrationPlate,
                                                            Model.CheckIn.Vehicle.Owner))
                        }
                        else
                        {
                            @Html.DisplayName(string.Format("Booked for {0} ({1})",
                                                            Model.CheckIn.Vehicle.RegistrationPlate,
                                                            Model.CheckIn.Vehicle.Owner))
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(model => model.ParkingSpot.Label)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ParkingSpot.VehicleType.Type)
                </td>
                <td>
                    @{
                        if (available || parked)
                        {
                            @Model.ParkingSpot.DisplayFee();
                        }
                        else
                        {
                            @Model.ParkingSpot.DisplayMonthlyFee();
                        }
                    }
                </td>
            </tr>
        </table>
    </div>

    <br />
    <br />

    <p>
        @if (available)
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.ParkingSpot.ID })<text> | </text>
        }
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

MVCGarage/Views/ParkingSpots/Edit.cshtml
@model MVCGarage.Models.ParkingSpot

@{
    ViewBag.Title = "Edit a Parking Spot";
}

<div class="header jumbotron">
    <h2>Edit a Parking Spot</h2>
    <hr />
    <p>This is where you can edit a parking spot</p>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal jumbotron" style="color: white;">
        <h1 style="text-align:center;">ParkingSpot</h1>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.VehicleTypeID,
                                      (IEnumerable<SelectListItem>)ViewBag.SelectVehicleTypes,
                                      htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr style="width: 50%; margin-left: 3em;" />

        <div class="form-group">
            @Html.LabelFor(model => model.Label, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Label, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr style="width: 50%; margin-left: 3em;" />

        <div class="form-group">
            @Html.LabelFor(model => model.Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ Html.EnableClientValidation(false); }
                @Html.EditorFor(model => model.Fee, new { htmlAttributes = new { @class = "form-control" } })
                @{ Html.EnableClientValidation(true); }
                @Html.ValidationMessageFor(model => model.Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
                    }

<div style="text-align:center; display: block; font-size: 2em; margin-bottom: 3em;">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCGarage/Views/ParkingSpots/Index.cshtml
@model IEnumerable<MVCGarage.ViewModels.Shared.DetailsParkingSpotVM>

@{
    ViewBag.Title = "Index";
}
<div class="header jumbotron">
    <h1>Parking spots</h1>
    <hr />
    <p>This is the list of available parking spots</p>
</div>

<p style="font-size: 2em; text-align: center;">
    @Html.ActionLink("Create a new parking spot", "Create")
</p>

<div class="index-table">
    <table>
        <tr>
            <th>
                @{string htmlName = @Html.DisplayNameFor(model => model.First().ParkingSpot.Label).ToHtmlString();}
                @Html.ActionLink(htmlName, "Index", new { sortOrder = ViewBag.LabelSortParam })
            </th>
            <th>
                @Html.ActionLink("Available?", "Index", new { sortOrder = ViewBag.AvailableSortParam })
            </th>
            <th>
                @{htmlName = @Html.DisplayNameFor(model => model.First().ParkingSpot.VehicleType).ToHtmlString();}
                @Html.ActionLink(htmlName, "Index", new { sortOrder = ViewBag.VehicleTypeSortParam })
            </th>
            <th>
                @{htmlName = @Html.DisplayNameFor(model => model.First().ParkingSpot.VehicleType.DefaultFee.Fee).ToHtmlString();}
                @Html.ActionLink(htmlName, "Index", new { sortOrder = ViewBag.FeeSortParam })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            bool available = false;
            bool parked = false;

            if (item.CheckIn == null)
            {
                available = true;
            }
            else
            {
                parked = !item.CheckIn.Booked;
            }

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ParkingSpot.Label)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Availability)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParkingSpot.VehicleType.Type)
                </td>
                <td>
                    @if (available || parked)
                    {
                        @item.ParkingSpot.DisplayFee();
                    }
                    else
                    {
                        @item.ParkingSpot.DisplayMonthlyFee();
                    }
                </td>
                <td>
                    @if (available)
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.ParkingSpot.ID })
                        <text> | </text>
                    }
                    else if (parked)
                    {
                        @Html.ActionLink("Check out",
                                         "CheckOutAVehicle",
                                         "Garage",
                                         new { vehicleId = item.CheckIn.VehicleID },
                                         null)
                        <text> | </text>
                    }
                    else
                    {
                        @Html.ActionLink("Unbook",
                                         "UnbookAParkingSpot",
                                         "Garage",
                                         new { vehicleId = item.CheckIn.VehicleID },
                                         null)
                        <text> | </text>
                    }
                    @Html.ActionLink("Details", "Details", new { id = item.ParkingSpot.ID })
                    @if (available)
                    {
                        <text> | @Html.ActionLink("Delete", "Delete", new { id = item.ParkingSpot.ID })
                        </text>
                    }
                    | @Html.ActionLink("View historic", "ParkingSpotHistoric", "CheckIns", new { parkingSpotId = item.ParkingSpot.ID }, null)
                </td>
            </tr>
        }

    </table>
</div>