MVCGarage/Models/CheckIn.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;

namespace MVCGarage.Models
{
    public class CheckIn
    {
        [Key]
        [Display(Name = "ID")]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Check in time")]
        public DateTime CheckInTime { get; set; }

        [Required]
        public bool Booked { get; set; }

        [Display(Name = "Check out time")]
        public DateTime? CheckOutTime { get; set; }

        [Display(Name = "Total Amount")]
        public double? TotalAmount { get; set; }

        // Navigation property - Allows the 1..1 relation to the "ParkingSpot" table
        [ForeignKey("ParkingSpot")]
        public int ParkingSpotID { get; set; }

        public virtual ParkingSpot ParkingSpot { get; set; }
        // --- //

        // Navigation property - Allows the 1..1 relation to the "Vehicle" table
        [ForeignKey("Vehicle")]
        public int VehicleID { get; set; }

        public virtual Vehicle Vehicle { get; set; }
        // --- //

        public string Status()
        {
            string status = string.Empty;

            if (CheckOutTime == null)
            {
                status = "Currently ";
            }

            if (Booked)
            {
                status += "Booked";
            }
            else
            {
                status += "Parked";
            }

            // Creates a TextInfo based on the "sv-SE" culture.
            return new CultureInfo("sv-SE", false).TextInfo.ToTitleCase(status);
        }

    }
}

MVCGarage/ViewModels/CheckIns/ParkingSpotHistoricVM.cs
using MVCGarage.Models;
using System.Collections.Generic;

namespace MVCGarage.ViewModels.CheckIns
{
    public class ParkingSpotHistoricVM
    {
        public ParkingSpot ParkingSpot { get; set; }
        public IEnumerable<CheckIn> CheckIns { get; set; }
    }
}

MVCGarage/ViewModels/CheckIns/ParkingSpotUnbooked.cs
using MVCGarage.Models;
using System;

namespace MVCGarage.ViewModels.CheckIns
{
    public class ParkingSpotUnbooked
    {
        public CheckIn CheckIn { get; set; }
        public DateTime CheckOutTime { get; set; }
        public int NbMonths { get; set; }
        public double TotalAmount { get; set; }
    }
}

MVCGarage/ViewModels/CheckIns/ParkingSpotUnbookedVM.cs
using MVCGarage.Models;
using System;

namespace MVCGarage.ViewModels.CheckIns
{
    public class ParkingSpotUnbookedVM
    {
        public CheckIn CheckIn { get; set; }
        public int NbMonths { get; set; }
    }
}

MVCGarage/ViewModels/CheckIns/VehicleCheckedOutVM.cs
using MVCGarage.Models;
using System;

namespace MVCGarage.ViewModels.CheckIns
{
    public class VehicleCheckedOutVM
    {
        public CheckIn CheckIn { get; set; }
        public int NbMinutes { get; set; }
    }
}

MVCGarage/ViewModels/CheckIns/VehicleHistoricVM.cs
using MVCGarage.Models;
using System.Collections.Generic;

namespace MVCGarage.ViewModels.CheckIns
{
    public class VehicleHistoricVM
    {
        public Vehicle Vehicle { get; set; }
        public IEnumerable<CheckIn> CheckIns { get; set; }
    }
}

MVCGarage/Controllers/GarageController.cs
using MVCGarage.Models;
using MVCGarage.Repositories;
using MVCGarage.ViewModels.Garage;
using MVCGarage.ViewModels.ParkingSpots;
using MVCGarage.ViewModels.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCGarage.Controllers
{
    public class GarageController : Controller
    {
        private VehiclesRepository vehicles = new VehiclesRepository();
        private ParkingSpotsRepository parkingSpots = new ParkingSpotsRepository();
        private CheckInsRepository checkIns = new CheckInsRepository();

        public Vehicle Vehicle(int? vehicleId)
        {
            return vehicles.Vehicle(vehicleId);
        }

        public ParkingSpot ParkingSpot(int? parkingSpotId)
        {
            return parkingSpots.ParkingSpot(parkingSpotId);
        }

        public List<Vehicle> BookedSpotsVehicles()
        {
            List<Vehicle> bookedSpotsVehicles = new List<Vehicle>();

            foreach (CheckIn checkIn in checkIns.CheckIns())
            {
                if (checkIn.Booked && checkIn.CheckOutTime == null)
                    bookedSpotsVehicles.Add(vehicles.Vehicle(checkIn.VehicleID));
            }

            return bookedSpotsVehicles;
        }

        private IEnumerable<Vehicle> Sort(IEnumerable<Vehicle> list, string sortOrder)
        {
            ViewBag.RegistrationPlateSortParam = string.IsNullOrEmpty(sortOrder) ? "regnum_desc" : "regnum_asc";
            ViewBag.OwnerSortParam = sortOrder == "owner_asc" ? "owner_desc" : "owner_asc";
            ViewBag.VehicleVehicleTypeSortParam = sortOrder == "vehicletype_asc" ? "vehicletype_desc" : "vehicletype_asc";
            ViewBag.VehicleCheckInTimeSortParam = sortOrder == "checkin_asc" ? "checkin_desc" : "checkin_asc";
            ViewBag.ParkingSpotSortParam = sortOrder == "spot_asc" ? "spot_desc" : "spot_asc";
            ViewBag.VehicleFeeSortParam = sortOrder == "fee_asc" ? "fee_desc" : "fee_asc";

            ViewBag.LabelSortParam = sortOrder == "label_asc" ? "label_desc" : "label_asc";
            ViewBag.AvailableSortParam = sortOrder == "available_asc" ? "available_desc" : "available_asc";
            ViewBag.VehicleTypeSortParam = sortOrder == "vehicletype_asc" ? "vehicletype_desc" : "vehicletype_asc";
            ViewBag.FeeSortParam = sortOrder == "fee_asc" ? "fee_desc" : "fee_asc";

            switch (sortOrder)
            {
                case "regnum_desc":
                    list = list.OrderByDescending(v => v.RegistrationPlate);
                    break;
                case "vehicletype_asc":
                    list = list.OrderBy(v => v.VehicleType.Type);
                    break;
                case "vehicletype_desc":
                    list = list.OrderByDescending(v => v.VehicleType.Type);
                    break;
                case "owner_asc":
                    list = list.OrderBy(v => v.Owner);
                    break;
                case "owner_desc":
                    list = list.OrderByDescending(v => v.Owner);
                    break;
                case "checkin_asc":
                    list = new CheckInsVehicles().InnerJoin(list)
                           .OrderBy(v_ch_p => v_ch_p.CheckIn == null)
                           .ThenBy(v_ch_p => GetCheckInTime(v_ch_p.CheckIn))
                           .Select(v_ch_p => v_ch_p.Vehicle);
                    break;
                case "checkin_desc":
                    list = new CheckInsVehicles().InnerJoin(list)
                           .OrderBy(v_ch_p => v_ch_p.CheckIn == null)
                           .ThenByDescending(v_ch_p => GetCheckInTime(v_ch_p.CheckIn))
                           .Select(v_ch_p => v_ch_p.Vehicle);
                    break;
                case "spot_asc":
                    list = new CheckInsVehicles().InnerJoin(list)
                           .OrderBy(v_ch_p => v_ch_p.CheckIn == null)
                           .ThenBy(v_ch_p => GetLabel(v_ch_p.ParkingSpot))
                           .Select(v_ch_p => v_ch_p.Vehicle);
                    break;
                case "spot_desc":
                    list = new CheckInsVehicles().InnerJoin(list)
                           .OrderBy(v_ch_p => v_ch_p.CheckIn == null)
                           .ThenByDescending(v_ch_p => GetLabel(v_ch_p.ParkingSpot))
                           .Select(v_ch_p => v_ch_p.Vehicle);
                    break;
                case "fee_asc":
                    list = new CheckInsVehicles().InnerJoin(list)
                           .OrderBy(v_ch_p => v_ch_p.CheckIn == null)
                           .ThenBy(v_ch_p => GetFee(v_ch_p))
                           .Select(v_ch_p => v_ch_p.Vehicle);
                    break;
                case "fee_desc":
                    list = new CheckInsVehicles().InnerJoin(list)
                           .OrderBy(v_ch_p => v_ch_p.CheckIn == null)
                           .ThenByDescending(v_ch_p => GetFee(v_ch_p))
                           .Select(v_ch_p => v_ch_p.Vehicle);
                    break;
                default:
                    list = list.OrderBy(v => v.RegistrationPlate);
                    break;
            }

            return list;
        }

        private DateTime GetCheckInTime(CheckIn checkIn)
        {
            if (checkIn == null)
                return new DateTime();
            else
                return (DateTime)checkIn.CheckInTime;
        }

        private string GetLabel(ParkingSpot spot)
        {
            if (spot == null)
                return string.Empty;
            else
                return spot.Label;
        }

        private double GetFee(InnerJoinResult innerJoin)
        {
            if (innerJoin.CheckIn == null)
                return 0;
            else if (innerJoin.CheckIn.Booked)
                return innerJoin.ParkingSpot.MonthlyFee();
            else
                return innerJoin.ParkingSpot.VehicleType.DefaultFee.Fee;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DisplayAllVehicles(string sortOrder)
        {
            Dictionary<int, CheckIn> dicParkingSpotsVehicles = new Dictionary<int, CheckIn>();

            foreach (Vehicle vehicle in vehicles.Vehicles())
            {
                dicParkingSpotsVehicles.Add(vehicle.ID, checkIns.CheckInByVehicle(vehicle.ID));
            }

            return View(new DisplayVehiclesVM
            {
                ViewName = "DisplayAllVehicles",
                Vehicles = Sort(vehicles.Vehicles(), sortOrder).ToList(),
                ParkingSpotsVehicles = dicParkingSpotsVehicles
            });
        }

        public ActionResult DisplayParkedVehicles(string sortOrder)
        {
            Dictionary<int, CheckIn> dicParkingSpots = new Dictionary<int, CheckIn>();

            List<Vehicle> parkedVehicles = new List<Vehicle>();

            foreach (Vehicle vehicle in vehicles.Vehicles())
            {
                CheckIn checkIn = checkIns.CheckInByVehicle(vehicle.ID);

                if (checkIn != null)
                {
                    parkedVehicles.Add(vehicle);
                    dicParkingSpots.Add(vehicle.ID, checkIn);
                }
            }

            return View(new DisplayVehiclesVM
            {
                ViewName = "DisplayParkedVehicles",
                Vehicles = Sort(parkedVehicles, sortOrder).ToList(),
                ParkingSpotsVehicles = dicParkingSpots
            });
        }

        public ActionResult UnbookAParkingSpot(int? vehicleId)
        {
            if (vehicleId == null)
                return RedirectToAction("UnbookParkingSpot",
                                        "Vehicles",
                                        new { errorMessage = "You must select a vehicle!" });

            return RedirectToAction("ParkingSpotUnbooked", "CheckIns", new { vehicleId = vehicleId });
        }

        public ActionResult CheckInAVehicle(int? vehicleId, string errorMessage)
        {
            Vehicle vehicle = vehicles.Vehicle(vehicleId);

            if (vehicle == null)
                return RedirectToAction("Index");

            return RedirectToAction("SelectAParkingSpot",
                                    "ParkingSpots",
                                    new
                                    {
                                        vehicleID = vehicle.ID,
                                        checkIn = true,
                                        errorMessage = errorMessage,
                                    });
        }

        public ActionResult CheckOutAVehicle(int? vehicleId)
        {
            if (vehicleId == null)
                return RedirectToAction("CheckOutVehicle",
                                        "Vehicles",
                                        new { errorMessage = "You must select a vehicle!" });

            return RedirectToAction("VehicleCheckedOut", "CheckIns", new { vehicleId = vehicleId });
        }

        public ActionResult Search(string searchedValue, string sortOrder)
        {
            if (string.IsNullOrEmpty(searchedValue))
                return RedirectToAction("Index");

            List<DetailsParkingSpotVM> foundParkingSpots = new List<DetailsParkingSpotVM>();
            ParkingSpotsController parkingSpotsController = new ParkingSpotsController();

            foreach (ParkingSpot foundParkingSpot in parkingSpotsController.Sort(parkingSpots.ParkingSpotsByIdentifiant(searchedValue), sortOrder))
            {
                CheckIn checkIn = checkIns.CheckInByParkingSpot(foundParkingSpot.ID);


MVCGarage/Views/CheckIns/ParkingSpotBooked.cshtml
@model MVCGarage.Models.CheckIn

@{
    ViewBag.Title = "Book A Parking Spot";
}

<div class="header jumbotron" style="color: white;">
    <h2>The following parking spot has been booked:</h2>
</div>

<div>
    <h4>Vehicle</h4>
    <hr />
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.RegistrationPlate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.Owner)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.VehicleType)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Vehicle.RegistrationPlate)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Vehicle.Owner)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Vehicle.VehicleType.Type)
                </td>
            </tr>
        </table>
    </div>
</div>

<div>
    <hr />
    <h4>Parking Spot</h4>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ParkingSpot.Label)
                </th>
                <th>
                    @Html.DisplayName("Check in time")
                </th>
                <th>
                    @Html.DisplayName("Monthly fee")
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.ParkingSpot.Label)
                </td>
                <td>
                    @Html.DisplayFor(model => model.CheckInTime)
                </td>
                <td>
                    @Model.ParkingSpot.DisplayMonthlyFee()
                </td>
            </tr>
        </table>
    </div>
</div>

<br />
<br />

<div style="text-align: center; font-size: 2em; display: block; margin-bottom: 3em; color: white;">
    <p>
        @Html.ActionLink("Back to List", "DisplayAllVehicles", "Garage")
    </p>
</div>

MVCGarage/Views/CheckIns/ParkingSpotUnbooked.cshtml
@model MVCGarage.ViewModels.CheckIns.ParkingSpotUnbookedVM

@{
    ViewBag.Title = "Unbook a Parking Spot";
}

<div class="header jumbotron">
    <h1>Unbooking</h1>
    <hr />
    <p>Your Parking Spot has been unbooked</p>
</div>

<div style="color: white; margin-top: 10em; text-align: center;">
    <h2 style="text-align: center;">Vehicle</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.Vehicle.RegistrationPlate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.Vehicle.Owner)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.Vehicle.VehicleType)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.Vehicle.RegistrationPlate)
                </td>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.Vehicle.Owner)
                </td>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.Vehicle.VehicleType.Type)
                </td>
            </tr>
        </table>
    </div>

    <hr />
    <h2 style="text-align: center;">Parking spot</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayName("Check in time")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.ParkingSpot.Label)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.ParkingSpot.Fee)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.CheckInTime)
                </td>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.ParkingSpot.Label)
                </td>
                <td>
                    @Model.CheckIn.ParkingSpot.DisplayMonthlyFee()
                </td>
            </tr>
        </table>
    </div>

    <hr />
    <h2 style="text-align: center;">Total amount</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayName("Check in time")
                </th>
                <th>
                    @Html.DisplayName("Check out time")
                </th>
                <th>
                    @Html.DisplayName("Total time")
                </th>
                <th>
                    @Html.DisplayName("Total amount")
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => Model.CheckIn.CheckInTime)
                </td>
                <td>
                    @Html.DisplayFor(model => Model.CheckIn.CheckOutTime)
                </td>
                <td>
                    @{ string s = string.Empty;
                     if (Model.NbMonths > 1)
                     { s = "s"; }
                    }
                    @Html.DisplayName(string.Format("{0} month{1}", Model.NbMonths, s))
                </td>
                <td>
                    @Html.DisplayFor(model => Model.NbMonths) *
                    @Html.DisplayName(string.Format("{0:N2}", Model.CheckIn.ParkingSpot.MonthlyFee())) =
                    @Html.DisplayName(string.Format("{0:C}", Model.CheckIn.TotalAmount))
                </td>
            </tr>
        </table>
    </div>
</div>

<div style="text-align: center; display: block; font-size: 2em; margin-bottom: 3em; color: white;">
    <p>
        @Html.ActionLink("Back to List", "DisplayAllVehicles", "Garage")
    </p>
</div>

MVCGarage/Views/CheckIns/VehicleCheckedIn.cshtml
@model MVCGarage.Models.CheckIn

@{
    ViewBag.Title = "Check in a vehicle";
}

<div class="header jumbotron">
    <h1>The following vehicle has been checked in:</h1>
</div>

<div class="about-body-text" style="color: white; margin-top: 10em; text-align: center;">
    <h2>Vehicle</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.RegistrationPlate)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.Owner)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.VehicleType)
                </th>
            </tr>

            <tr>
                <td>
                    @Html.DisplayFor(model => model.Vehicle.RegistrationPlate)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Vehicle.Owner)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Vehicle.VehicleType.Type)
                </td>
            </tr>
        </table>
    </div>

    <hr />
    <h2>Parking Spot</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ParkingSpot.Label)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.ParkingSpot.Fee)
                </th>

                <th>
                    @Html.DisplayName("Check in time")
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.ParkingSpot.Label)
                </td>

                <td>
                    @Model.ParkingSpot.DisplayFee()
                </td>

                <td>
                    @Html.DisplayFor(model => model.CheckInTime)
                </td>
            </tr>
        </table>
    </div>
</div>

<div style="color: white; text-align: center; display: block; font-size: 2em; margin-bottom: 3em;">
    <p>
        @Html.ActionLink("Back to List", "DisplayAllVehicles", "Garage")
    </p>
</div>

MVCGarage/Views/CheckIns/VehicleCheckedOut.cshtml
@model MVCGarage.ViewModels.CheckIns.VehicleCheckedOutVM

@{
    ViewBag.Title = "Check out a vehicle";
}

<div class="header jumbotron">
    <h1>Check Out</h1>
    <hr />
    <p>Your Vehicles has been checked out</p>
</div>

<div style="color: white; margin-top: 10em; text-align: center;">
    <h2 style="text-align: center;">Vehicle</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.Vehicle.RegistrationPlate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.Vehicle.Owner)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.Vehicle.VehicleType)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.Vehicle.RegistrationPlate)
                </td>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.Vehicle.Owner)
                </td>
                <td>
                    @Html.DisplayFor(model=> model.CheckIn.Vehicle.VehicleType.Type)
                </td>
            </tr>
        </table>
    </div>

    <hr />
    <h2 style="text-align: center;">Parking spot</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayName("Check in time")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.ParkingSpot.Label)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CheckIn.ParkingSpot.Fee)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.CheckInTime)
                </td>
                <td>
                    @Html.DisplayFor(model => model.CheckIn.ParkingSpot.Label)
                </td>
                <td>
                    @Model.CheckIn.ParkingSpot.DisplayFee()
                </td>
            </tr>
        </table>
    </div>

    <hr />
    <h2 style="text-align: center;">Total amount</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayName("Check in time")
                </th>
                <th>
                    @Html.DisplayName("Check out time")
                </th>
                <th>
                    @Html.DisplayName("Total time")
                </th>
                <th>
                    @Html.DisplayName("Total amount")
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => Model.CheckIn.CheckInTime)
                </td>
                <td>
                    @Html.DisplayFor(model => Model.CheckIn.CheckOutTime)
                </td>
                <td>
                    @Html.DisplayName(TimeSpan.FromMinutes(Model.NbMinutes).ToString())
                </td>
                <td>
                    @Html.DisplayFor(model => Model.NbMinutes) *
                    @Html.DisplayName(string.Format("{0:N2}", Model.CheckIn.ParkingSpot.GetFee())) =
                    @Html.DisplayName(string.Format("{0:C}", Model.CheckIn.TotalAmount))
                </td>
            </tr>
        </table>
    </div>
</div>

<div style="text-align: center; display: block; font-size: 2em; margin-bottom: 3em; color: white;">
    <p>
        @Html.ActionLink("Back to List", "DisplayAllVehicles", "Garage")
    </p>
</div>

MVCGarage/Views/CheckIns/VehicleHistoric.cshtml
@model MVCGarage.ViewModels.CheckIns.VehicleHistoricVM

@{
    ViewBag.Title = "Parking Historic";
}

<div class="header jumbotron">
    <h1>Parking Historic for:</h1>
</div>

<div style="color: white; margin-top: 10em; text-align: center;">
    <h2 style="text-align: center;">Vehicle</h2>
    <div class="index-table">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.RegistrationPlate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.Owner)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.VehicleType)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Vehicle.RegistrationPlate)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Vehicle.Owner)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Vehicle.VehicleType.Type)
                </td>
            </tr>
        </table>
    </div>

    @if (Model.CheckIns.Count() == 0)
    {
        <h2>No historic to be displayed</h2>
    }
    else
    {
        <hr />

        <h2 style="text-align: center;">Parking Spots</h2>
        <div class="index-table">
            <table>
                <tr>
                    <th>
                        @{string htmlName = @Html.DisplayNameFor(model => model.CheckIns.First().ParkingSpot.Label).ToHtmlString();}
                        @Html.ActionLink(htmlName,
                                         "VehicleHistoric",
                                         new
                                         {
                                             vehicleId = Model.CheckIns.First().VehicleID,
                                             sortOrder = ViewBag.ParkingSpotLabelSortParam
                                         })
                    </th>
                    <th>
                        @{htmlName = @Html.DisplayNameFor(model => model.CheckIns.First().CheckInTime).ToHtmlString();}
                        @Html.ActionLink(htmlName,
                                         "VehicleHistoric",
                                         new
                                         {
                                             vehicleId = Model.CheckIns.First().VehicleID,
                                             sortOrder = ViewBag.CheckInTimeSortParam
                                         })
                    </th>
                    <th>
                        @{htmlName = @Html.DisplayNameFor(model => model.CheckIns.First().CheckOutTime).ToHtmlString();}
                        @Html.ActionLink(htmlName,
                                         "VehicleHistoric",
                                         new
                                         {
                                             vehicleId = Model.CheckIns.First().VehicleID,
                                             sortOrder = ViewBag.CheckOutTimeSortParam
                                         })
                    </th>
                    <th>
                        @{htmlName = @Html.DisplayNameFor(model => model.CheckIns.First().TotalAmount).ToHtmlString();}
                        @Html.ActionLink(htmlName,
                                         "VehicleHistoric",
                                         new
                                         {
                                             vehicleId = Model.CheckIns.First().VehicleID,
                                             sortOrder = ViewBag.TotalAmountSortParam
                                         })
                    </th>
                    <th>
                        @Html.ActionLink("Status",
                                         "VehicleHistoric",
                                         new
                                         {
                                             vehicleId = Model.CheckIns.First().VehicleID,
                                             sortOrder = ViewBag.StatusSortParam
                                         })
                    </th>
                </tr>

                @foreach (var item in Model.CheckIns)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ParkingSpot.Label)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CheckInTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CheckOutTime)
                        </td>
                        <td>
                            @Html.DisplayName(string.Format("{0:C}", item.TotalAmount))
                        </td>
                        <td>
                            @Html.DisplayName(item.Status())
                        </td>
                    </tr>
                }
            </table>
        </div>
    }
</div>

<div style="color: white; text-align: center; display: block; font-size: 2em; margin-bottom: 3em;">
    <p>
        @Html.ActionLink("Back to List", "DisplayAllVehicles", "Garage")
    </p>
</div>